eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka1

server:
  port: 8761





